book-liby-dev/config/routes.rb
Rails.application.routes.draw do

  # Rout request come in to its demo contoller and index action
  #then contoller has an action, and rendering the view
  #root route
  root 'books#index'

  #simple route
 get 'demo/index'
 get 'demo/hello'


  resources :books do
    member do
      get :delete
    end
  end
 #get 'books/index'
 #get 'books/show'
 #get 'books/new'
 #get 'books/edit'
 #get 'books/delete'


  #default route
 #get ':controller(/:action(/:id))'


end

book-liby-dev/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book-liby-dev/app/models/book.rb
class Book < ApplicationRecord
end

book-liby-dev/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

book-liby-dev/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
      @bks = Book.all    #query db ascending order
        flash.now[:notice] = "We have exactly #{@bks.size} books available."
  end

  def show
    @bks = Book.find(params[:id])
  end

  def new
    @bks = Book.new
  end

  def create
    #new object for passing in
    @bks = Book.new(book_params)
    #save the object
    if @bks.save
    flash.now[:alert] = 'Alert message!'
     redirect_to (books_path) #go back to index pager
    else

      #render('new') #render the tempalte for user to fix, not calling new again
      render ('new')
    end
  end

  def edit
    @bks = Book.find(params[:id])
  end

  def update
    @bks = Book.find(params[:id])
    if @bks.update(book_params)
      redirect_to(book_path(@bks))
    else
      render('edit')
    end

  end

  def delete
    @bks = Book.find(params[:id])

  end

  def destroy
    @bks = Book.find(params[:id])
    @bks.destroy
    redirect_to(books_path)
  end

  private
      def book_params
        params.require(:book).permit(:title,:author,:genre,:price,:published_date)
      end

end

book-liby-dev/app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false

  def index #an action
    #render('demo/index') #省略html.erb后缀
  end

  def hello
    @array = [1,2,3,4]
  #  @id = params['id']
  #  @page = params[:page]

    if params[:id]== '4'
      @phone = '12345678'
    elsif params[:id]  == '5'
      @phone = 'xxxxxxxx'
    else
      @phone = '1111111'
    end


   #render('demo/hello') #也可以不写，这个是default
  #  redirect_to('https://nytimes.com')
   #redirect_to(controller:'demo', action:'index')
  end
end

book-liby-dev/app/helpers/application_helper.rb
module ApplicationHelper
end

book-liby-dev/app/helpers/books_helper.rb
module BooksHelper
end

book-liby-dev/app/helpers/demo_helper.rb
module DemoHelper
end

book-liby-dev/app/views/books/delete.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete A Book</h2>

  <%= form_for(@bks, :method => 'delete') do |f| %>

    <p>Are you sure that you want to permanently delete the book?</p>
    <p><%= @bks.title %></p>
    <div class="form-buttons">
      <%= f.submit("Delete Book") %>
    </div>

  <% end %>
</div>

book-liby-dev/app/views/books/edit.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Update Book</h2>

  <%= form_for(@bks) do |f| %> <!-- rails knows to do path here automatically -->

    <table summary="Book edit">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.text_field(:genre) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.text_field(:published_date) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>

  <% end %>
</div>

book-liby-dev/app/views/books/index.html.erb
<div class="books index">
  <h2>Books Listing Below</h2>

  <%= link_to("Add New Books", new_book_path, :class => 'action new') %>

  <table class="listing" summary="Book list">
    <tr class="header">
      <th>#</th>
      <th>Title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
    <th>Published Date</th>
    </tr>

    <% @bks.each do |bk| %>
    <tr>
      <td><%= bk.id%></td>
      <td><%= bk.title%></td>
      <td><%= bk.author%></td>
      <td class="center"><%= bk.genre%></td>
      <td class="center"><%= bk.price%></td>
      <td class="center"><%= bk.published_date %></td>
      <td class="actions">
        <%= link_to("Show", book_path(bk), :class => 'action show') %>
        <%= link_to("Edit", edit_book_path(bk), :class => 'action edit') %>
        <%= link_to("Delete", delete_book_path(bk), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

book-liby-dev/app/views/books/new.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create A New Book!</h2>

  <%= form_for(@bks, :url => books_path, :method => 'post') do |f| %>

    <table summary="Subject form fields">
      <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th>Author</th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th>Genre</th>
        <td><%= f.text_field(:genre) %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field(:price) %></td>
      </tr>
      <tr>
        <th>Published Date</th>
        <td><%= f.text_field(:published_date) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Book") %>
    </div>

  <% end %>
</div>

book-liby-dev/app/views/books/show.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books show">
  <h2>Show Subject</h2>

  <table summary="Book detailed view">
    <tr>
      <th>Title</th>
      <td><%= @bks.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @bks.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @bks.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @bks.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @bks.published_date %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @bks.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @bks.updated_at %></td>
    </tr>
  </table>

</div>

book-liby-dev/app/views/demo/hello.html.erb
<h1>HELLO everyone!</h1>

<%= 1+1 %>


<% @array.each do |n| %>
<p><%= n %></p>
<%end%>

<%= @array %>
<br \>
<%= link_to("Click here to go back to index page",{:controller => 'demo', :action => 'index'}) %>
<br \>
ID: <%=@id%>
<br \>
Page: <%=@page%>
<br \>
Next page: <%=@page.to_i + 1%>
<br \>
Phone number: <%=@phone%>

book-liby-dev/app/views/demo/index.html.erb
<h1>HELLO Qingboyuan !</h1>

<a href="/demo/hello">Click here to hello page </a> <br />

<%= link_to("Also Click here to hello page",{:controller => 'demo', :action => 'hello'}) %> <br />

<%= link_to("Click here to hello page with parameters",{:controller => 'demo', :action => 'hello', :page => 3, :id => 3}) %>
<br />
<!-- <%= link_to("All books",books_path)%> -->

book-liby-dev/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>